from enum import Enum

class PrefixText(Enum):
    WEIGHT_PREFIX = "WeightPrefix"
    WEIGHT_SUFFIX = "WeightSuffix"
    DAMAGE_PREFIX = "DamagePrefix"

class UIText(Enum):
    APP_TITLE = "AppTitle"
    BUTTON_ITEMS = "ItemsButton"
    BUTTON_SPELLS = "SpellsButton"
    BUTTON_ADD_SPELL = "AddSpellButton"
    BUTTON_MANAGE_SPELLS = "ManageSpellsButton"
    BUTTON_PRINT_SPELLS = "PrintSpellsButton"
    BUTTON_ADD_ITEM = "AddItemButton"
    BUTTON_MANAGE_ITEMS = "ManageItemsButton"
    BUTTON_PRINT_ITEMS = "PrintItemsButton"
    BUTTON_BACK = "BackButton"
    SPELLS_NOT_IMPLEMENTED = "SpellsNotImplemented"
    MANAGE_ITEMS_TITLE = "ManageItemsTitle"
    SEARCH_LABEL = "SearchLabel"
    SORT_BY_LABEL = "SortByLabel"
    COLUMN_ID = "ColumnID"
    COLUMN_NAME = "ColumnName"
    COLUMN_PRICE = "ColumnPrice"
    COLUMN_WEIGHT = "ColumnWeight"
    BUTTON_VIEW_CARD = "ViewCardButton"
    BUTTON_EDIT_DATA = "EditDataButton"
    BUTTON_EDIT_CARD = "EditCardButton"
    BUTTON_CLOSE = "CloseButton"
    ADD_ITEM_TITLE = "AddItemTitle"
    EDIT_ITEM_TITLE = "EditItemTitle"
    DAMAGE_LABEL = "DamageLabel"
    ATTRIBUTES_LABEL = "AttributesLabel"
    SAVE_BUTTON = "SaveButton"
    ITEM_PREVIEW_TITLE = "ItemPreviewTitle"
    BUTTON_FLIP = "FlipButton"
    BUTTON_SKIP = "SkipButton"
    BUTTON_NEXT = "NextButton"
    MANAGE_SPELLS_TITLE = "ManageSpellsTitle"
    ADD_SPELL_TITLE = "AddSpellTitle"
    EDIT_SPELL_TITLE = "EditSpellTitle"
    SPELL_PREVIEW_TITLE = "SpellPreviewTitle"

class MessageText(Enum):
    NO_SELECTION_TITLE = "NoSelectionTitle"
    NO_SELECTION_TEXT = "NoSelectionText"
    ERROR_TITLE = "ErrorTitle"
    SAVED_TITLE = "SavedTitle"
    ITEM_SAVED = "ItemSaved"
    NO_ITEMS_TITLE = "NoItemsTitle"
    NO_ITEMS_MESSAGE = "NoItemsMessage"
    PREVIEW_MODE = "PreviewMode"
    PREVIEW_QUESTION = "PreviewQuestion"
    DONE_TITLE = "DoneTitle"
    DONE_MESSAGE = "DoneMessage"
    MISSING_IMAGE_TITLE = "MissingImageTitle"
    MISSING_IMAGE_MESSAGE = "MissingImageMessage"
    INVALID_RANGE = "InvalidRange"
    INVALID_VALUE = "InvalidValue"
    ID_NAME_REQUIRED = "IDNameRequired"
